version: '3.1'
services:
  wizcloud-ansible-deployer:
  # build this local dockerfile (current working directory)
    build:
      context: .
    environment:
      - SSH_PRIVATE_KEY
#      - VAULT_PASSWORD
    #image: wizcloud-ansible-deployer:1.0
    # harbor registry container
    image: reg.wizznet.co.uk:80/wizznet/wizcloud-ansible-deployer
#    env_file: .env
    container_name: wizcloud-ansible-deployer
    hostname: wizcloud-ansible-deployer
    restart: "no"
    privileged: true
    entrypoint: ['ansible-playbook', '-i', 'inventory.ini', 'day0.yml']
    networks:
      wizcloud:
        ipv4_address: 172.31.0.4
    volumes:
      - /root/.vault_password:/root/.vault_password
      - /root/.ssh/config:/root/.ssh/config
      - /root/.ssh/id_troon:/root/.ssh/id_troon

networks:
  wizcloud:
    ipam:
      driver: default
      config:
        - subnet: "172.31.0.0/24"
